### ISSUE TITLE
Upgrade to 1.3.5 result in Whitelabel Error Page

### ISSUE THREAD

**Issue by ermicioi** [mariuszs/spring-boot-web-jsp-example#1]
If upgrade the pom to use spring boot 1.3.5 then when opening the application it is displayed a page with following content:

_Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Thu Jun 23 22:41:46 CEST 2016
There was an unexpected error (type=Not Found, status=404).
No message available_ 

Any idea how it can be solved?

**Comment by mariuszs** [comment]
I have updated this project to 2.0.4, check if this helps you.
