### ISSUE TITLE
When you run it, you'll get this error page. It looks like cannot find jsp file inside jar file.

### ISSUE THREAD

**Issue by hasanmirzae** [mariuszs/spring-boot-web-jsp-example#2]
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Sun Jul 03 22:26:56 MSK 2016
There was an unexpected error (type=Not Found, status=404).
/WEB-INF/jsp/index.jsp

**Comment by TrumanDu** [comment]
@hasanmirzae [see here](http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-developing-web-applications.html#boot-features-jsp-limitations)

**Comment by NextPoorSlob** [comment]
Move the JSPs to "src/main/resources/META-INF/resources/WEB-INF/jsp".
Make sure the application.properties file contains:
spring.view.prefix: /WEB-INF/jsp/
spring.view.suffix: .jsp

It should then work.

**Comment by lhazlewood** [comment]
This sample project *does not work*.

Proof:

```bash
git clone https://github.com/mariuszs/spring-boot-web-jsp-example.git
cd spring-boot-web-jsp-example
mvn clean package
java -jar target/jsp-boot-tst-1.0-SNAPSHOT.jar
```

The above _appears_ to work when you visit localhost:8080 - but the solution is directory dependent and is not portable.  Try this (by going up one directory):

```bash
cd ..
java -jar spring-boot-web-jsp-example/target/jsp-boot-tst-1.0-SNAPSHOT.jar
```

and then visit localhost:8080.  This time, you'll see the following:

```
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Wed Jul 19 13:22:49 EDT 2017
There was an unexpected error (type=Not Found, status=404).
/WEB-INF/jsp/index.jsp
```

This means you cannot take the resulting .jar file and put it on a production machine without also taking the directory assets.  I.e. it's not reasonably portable and not a sufficient solution for a spring boot executable jar with jsps

**Comment by lhazlewood** [comment]
Follow up:

I did as @NextPoorSlob recommended and it worked.

*However*:

The recommendation only works up to/including Spring Boot 1.2.8.

The instant you upgrade to Spring Boot 1.3.0 or later, the jar is no longer self contained and is not suitable for distribution.

**Comment by bhsc881114** [comment]
+1,have no clue

**Comment by shankar96** [comment]
Faced same issue
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Fri Jun 22 08:11:49 GMT 2018
There was an unexpected error (type=Not Found, status=404).
/WEB-INF/jsp/configuration.jsp

**Comment by mrk12712** [comment]
Faced the same issue when spring boot version is 1.5.9 and it is working fine when spring boot version is 1.4.3 and i don't know why? any one please reply

Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Wed Jul 04 18:21:06 IST 2018
There was an unexpected error (type=Not Found, status=404).
/services/login.jsp

**Comment by ManojRamanan** [comment]
+1

**Comment by ghost** [comment]
+1
Same problem, impossible for an executable jar of spring boot 2 project

**Comment by mariuszs** [comment]
Strange, because this works for me ;)

    ./mvnw clean package 
    java -jar target/jsp-boot-tst-1.0-SNAPSHOT.jar
    curl -i http://localhost:8080/     
                                                                         
```xml
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
Set-Cookie: JSESSIONID=F47295C9A5C588FFAC075CD0D5A5CAD8; Path=/; HttpOnly
Content-Type: text/html;charset=UTF-8
Content-Language: pl-PL
Content-Length: 300
Date: Wed, 29 Aug 2018 12:15:10 GMT

<!DOCTYPE html>


<html lang="en">

<body>
    <h1>Hello World</h1>

    
    

    <p><a href="/test.txt;jsessionid=F47295C9A5C588FFAC075CD0D5A5CAD8">URL generated by Spring</a></p>
    <p><a href="/test.txt;jsessionid=F47295C9A5C588FFAC075CD0D5A5CAD8">URL generated by JSTL</a></p>
</body>

</html>⏎ 

```

**Comment by kvh44** [comment]
This application has no explicit mapping for /error, so you are seeing this as a fallback

**Comment by kvh44** [comment]
I have found the problem.  When you execute the generated jar file of spring boot. You need to execute the command out of the folder target like this 

" mvn clean package && java -jar target/mmm-0.0.1-SNAPSHOT.jar". 

Otherwise it can't find the folder WEB-INF which located in "/src/main/webapp/".

**Comment by NextPoorSlob** [comment]
I have three last comments:
1.  Thank you, Mariusz Smykuła, for creating this example.  It got me over a difficult problem when I could not find a solution under an extremely tight deadline.
2. There is a decent replacement for JSP pages called [Thymeleaf Templates](https://www.thymeleaf.org/index.html).  It does require moving a lot of the <%= ... =%> coding into the controller, but I find converting JSP's to this tool a quicker solution than rewriting the application to some flavor of JavaScript like Angular or REACT.
3. Thank you, Mariusz Smykuła!
